///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest75
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest75Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("20622c72-56f2-4eab-aebf-572a5ed8492d")]
    public partial class MyTest75Repository : RepoGenBaseFolder
    {
        static MyTest75Repository instance = new MyTest75Repository();
        MyTest75RepositoryFolders.RxMainFrameAppFolder _rxmainframe;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest75Repository element repository.
        /// </summary>
        [RepositoryFolder("20622c72-56f2-4eab-aebf-572a5ed8492d")]
        public static MyTest75Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest75Repository() 
            : base("MyTest75Repository", "/", null, 0, false, "20622c72-56f2-4eab-aebf-572a5ed8492d", ".\\RepositoryImages\\MyTest75Repository20622c72.rximgres")
        {
            _rxmainframe = new MyTest75RepositoryFolders.RxMainFrameAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("20622c72-56f2-4eab-aebf-572a5ed8492d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The RxMainFrame folder.
        /// </summary>
        [RepositoryFolder("80861248-edde-4e81-ba31-7ea8be00aee2")]
        public virtual MyTest75RepositoryFolders.RxMainFrameAppFolder RxMainFrame
        {
            get { return _rxmainframe; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest75RepositoryFolders
    {
        /// <summary>
        /// The RxMainFrameAppFolder folder.
        /// </summary>
        [RepositoryFolder("80861248-edde-4e81-ba31-7ea8be00aee2")]
        public partial class RxMainFrameAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _txtusernameInfo;

            /// <summary>
            /// Creates a new RxMainFrame  folder.
            /// </summary>
            public RxMainFrameAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RxMainFrame", "/form[@controlname='RxMainFrame']", parentFolder, 30000, null, true, "80861248-edde-4e81-ba31-7ea8be00aee2", "")
            {
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", "?/?/tabpage[@controlname='RxTabIntroduction']/text[@controlname='txtUserName']", ".//text[@controlname='txtUserName']", 30000, null, "e77a2cbd-81f0-4976-879d-1e9d159cf12a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("80861248-edde-4e81-ba31-7ea8be00aee2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("80861248-edde-4e81-ba31-7ea8be00aee2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("e77a2cbd-81f0-4976-879d-1e9d159cf12a")]
            public virtual Ranorex.Text TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("e77a2cbd-81f0-4976-879d-1e9d159cf12a")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
